import React, { useEffect, useState } from 'react';
import { useAppStore } from '../store';
import { generateArchitecture } from '../services/geminiService';
import { Mermaid } from '../components/Mermaid';
import { Loader2, RefreshCw } from 'lucide-react';

export const Architecture: React.FC = () => {
  const { currentRepo, analysis } = useAppStore();
  const [diagram, setDiagram] = useState<{ mermaidCode: string, explanation: string } | null>(null);
  const [loading, setLoading] = useState(false);

  const fetchDiagram = async () => {
    if (!currentRepo || !analysis) return;
    setLoading(true);
    try {
      const result = await generateArchitecture(currentRepo.files.map(f => f.path), analysis);
      setDiagram(result);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // Only fetch if we haven't yet or if explicit refresh
    if (!diagram && currentRepo && analysis) {
      fetchDiagram();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentRepo, analysis]);

  if (!currentRepo) return <div className="text-center mt-20 text-slate-500">Analyze a repo first.</div>;

  return (
    <div className="h-full flex flex-col">
       <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Architecture Diagram</h2>
          <p className="text-slate-500">Visual map of components and data flow generated by Gemini</p>
        </div>
        <button 
          onClick={fetchDiagram} 
          disabled={loading}
          className="flex items-center gap-2 text-brand-600 hover:text-brand-700 font-medium disabled:opacity-50"
        >
          <RefreshCw size={18} className={loading ? "animate-spin" : ""} />
          Regenerate
        </button>
      </div>

      {loading && (
        <div className="flex flex-col items-center justify-center h-64">
           <Loader2 className="animate-spin text-brand-600 mb-4" size={40} />
           <p className="text-slate-500">Analyzing structure and generating diagram...</p>
        </div>
      )}

      {!loading && diagram && (
        <div className="space-y-6">
           <Mermaid chart={diagram.mermaidCode} />
           
           <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
             <h3 className="font-semibold text-slate-800 mb-2">Explanation</h3>
             <p className="text-slate-600 leading-relaxed">{diagram.explanation}</p>
           </div>

           <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
             <h4 className="text-xs font-bold text-slate-500 uppercase mb-2">Mermaid Source</h4>
             <pre className="text-xs text-slate-600 overflow-x-auto whitespace-pre-wrap">
               {diagram.mermaidCode}
             </pre>
           </div>
        </div>
      )}
    </div>
  );
};