import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { useAppStore } from '../store';
import { fetchFileContent } from '../services/githubService';
import { createPRPatch } from '../services/geminiService';
import { Task, BugReport, GeneratedPatch } from '../types';
import { Loader2, GitPullRequest, Copy, Check } from 'lucide-react';

export const PRGenerator: React.FC = () => {
  const location = useLocation();
  const { currentRepo } = useAppStore();
  const [source, setSource] = useState<Task | BugReport | null>(null);
  const [selectedFile, setSelectedFile] = useState('');
  const [patch, setPatch] = useState<GeneratedPatch | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (location.state?.task) {
        setSource(location.state.task);
    } else if (location.state?.bug) {
        setSource(location.state.bug);
        setSelectedFile(location.state.bug.filePath);
    }
  }, [location.state]);

  const handleGenerate = async () => {
    if (!source || !selectedFile || !currentRepo) return;
    setLoading(true);
    try {
      const content = await fetchFileContent(currentRepo.owner, currentRepo.repo, selectedFile);
      const result = await createPRPatch(source, content, selectedFile);
      setPatch(result);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (patch) {
      navigator.clipboard.writeText(patch.diff);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (!currentRepo) return <div className="text-center mt-20 text-slate-500">Analyze a repo first.</div>;

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-2">
        <GitPullRequest className="text-brand-600" /> Auto PR Generator
      </h2>

      <div className="grid grid-cols-1 gap-6 mb-8">
        <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
          <label className="block text-sm font-medium text-slate-700 mb-2">Target Issue / Task</label>
          <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 mb-4">
             {source ? (
               <>
                 <span className="font-bold block mb-1">{(source as Task).title || (source as BugReport).issueType}</span>
                 <span className="text-sm text-slate-600">{source.description}</span>
               </>
             ) : (
               <span className="text-slate-400 italic">No task selected. Go to Tasks or Bug Scan to select one.</span>
             )}
          </div>

          <label className="block text-sm font-medium text-slate-700 mb-2">Target File to Patch</label>
          <select 
            value={selectedFile} 
            onChange={(e) => setSelectedFile(e.target.value)}
            className="w-full p-3 border border-slate-300 rounded-lg bg-white focus:ring-2 focus:ring-brand-500 outline-none"
          >
            <option value="">Select a file...</option>
            {currentRepo.files.map(f => (
              <option key={f.path} value={f.path}>{f.path}</option>
            ))}
          </select>
          
          <button 
            onClick={handleGenerate}
            disabled={!source || !selectedFile || loading}
            className="mt-6 w-full bg-brand-600 hover:bg-brand-700 disabled:bg-slate-300 text-white font-bold py-3 rounded-lg transition-colors flex justify-center items-center gap-2"
          >
            {loading ? <Loader2 className="animate-spin" /> : <GitPullRequest size={20} />}
            Generate Patch
          </button>
        </div>
      </div>

      {patch && (
        <div className="bg-white border border-slate-200 rounded-xl shadow-lg overflow-hidden animate-fade-in">
           <div className="bg-slate-50 border-b border-slate-200 p-4 flex justify-between items-center">
             <div>
               <h3 className="font-bold text-slate-800">{patch.commitMessage}</h3>
               <p className="text-sm text-slate-500 mt-1">Generated by DevPilot AI</p>
             </div>
             <button 
               onClick={copyToClipboard}
               className="flex items-center gap-2 px-3 py-1.5 bg-white border border-slate-300 rounded text-sm font-medium hover:bg-slate-50 transition-colors"
             >
               {copied ? <Check size={16} className="text-green-600"/> : <Copy size={16} className="text-slate-600"/>}
               {copied ? "Copied" : "Copy Diff"}
             </button>
           </div>
           
           <div className="p-4 bg-slate-50 border-b border-slate-200">
             <h4 className="text-xs font-bold text-slate-500 uppercase mb-2">PR Description</h4>
             <p className="text-slate-700 text-sm whitespace-pre-wrap">{patch.description}</p>
           </div>

           <div className="bg-[#0d1117] p-4 overflow-x-auto">
             <pre className="text-green-400 font-mono text-sm leading-relaxed">
               {patch.diff}
             </pre>
           </div>
        </div>
      )}
    </div>
  );
};